name: build docker image containing numpy
on:
  workflow_dispatch:

jobs:
  my-job:
    name: build docker image containing numpy
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: build and save the image
        run: "docker image build -t build1 .; docker save build1 > savedImage.tar; ls -sh savedImage.tar"
