name: run without docker
on:
  workflow_dispatch:

jobs:
  my-job:
    name: run the code
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: put dedalus2 in the right spot
        run: mv files/dedalus2 /usr/share/miniconda/envs
      - name: try starting the dedalus environment
        run: source activate dedalus2
      - name: try running the python code
        run: cd files; python3 search.py
