name: build docker image containing numpy
on:
  workflow_dispatch:

jobs:
  my-job:
    name: run artifact docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
        
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: list files
        run: 'ls'
