name: run docker image
on:
  workflow_dispatch:

jobs:
  my-job:
    name: test if we have docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: assemble the tar file
        run: python partition a 1.8 savedImageParts image.tar
      - name: load the tar file
        run: docker load < image.tar
      - name: run the loaded image
        run: docker run build1
        
