name: run large docker image
on:
  workflow_dispatch:

jobs:
  my-job:
    name: test if we have docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: construct the tar file
        run: cat eg* > image.tar
      - name: load the tar file
        run: "docker load < image.tar"
      - name: run the loaded image
        run: "docker run pyimg15"

