name: testing conda
on:
  workflow_dispatch:

jobs:
  my-job:
    name: testing conda
    runs-on: ubuntu-latest
    steps:
      - name: do I have python and conda?
        run: "conda"
        
        
