name: testing docker
on:
  workflow_dispatch:

jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: do I have python and conda?
        run: "python3 -V"
        
        
